name: Test Secrets

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use secret
        run: |
          echo "The secret is \${{ secrets.SECRET }}"

